name: Build CI

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  Build:
    uses: ./.github/workflows/build.yml
    with:
      variant: Debug
    secrets:
      RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
      RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
      RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}